<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;




/*function signup_user_presave(UserInterface $user) {
    if ($user->isNew() && !$user->hasRole('unverified account')) {
        $admin = FALSE;

        foreach ($user->getRoles(TRUE) as $id) {
            $role = Role::load($id);
            if ($role->isAdmin()) {
                $admin = TRUE;
                break;
            }
        }

        if (!$admin) {
            $user->addRole('unverified account');
        }
    }
}*/


function signup_user_presave(EntityInterface $user) {
    if($user->isNew()) {
        $user->addRole('participant');
    }
}



/**
 * Implements hook_mail().
 */
function workshopfactory_mail($key, &$message, $params) {
$options = array(
  'langcode' => $message['langcode'],
);
 switch ($key) {
   case 'send_mail':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('This is a test subject', $options);
     $message['body'][] = $params['message'];
   drupal_set_message('Key valide');

     break;
 }
}


///**
// * Implements hook_mail().
// */
//function workshopfactory_mail($key, &$message, $params) {
//  switch ($key) {
//    case 'my_key':
//      $message['from'] = \Drupal::config('system.site')->get('mail');
//      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
//      $message['subject'] = $params['subject'];
//      $message['body'][] = 'Test';
//      //$message['body'][] = $params['message'];
//      $message['options'] = [];
//      if (isset($params['options']) && !empty($params['options'])) {
//        foreach ($params['options'] as $key => $value) {
//          $message['options'][$key] = $value;
//        }
//      }
//      break;
//  }
//}

///**
// * Implements hook_mail_alter().
// */
//function workshopfactory_mail_alter(&$message) {
//  switch ($message['key']) {
//    case 'my_key':
//      if ( /* Some conditions. */ ) {
//        $message['body'][] = t('Additionnal message');
//      }
//      if ( /* Another condition. */ ) {
//        $message['send'] = FALSE;
//      }
//      break;
//  }
//}

/**
 * Implements hook_theme().
 */
//function workshopfactory_theme($existing, $type, $theme, $path) {
//  return [
//    'workshopfactory_courriel' => [
//      'template' => 'mail',
//      'variables' => [
//        'message' => array(),
//      ],
//    ],
//  ];
//}